### ISSUE TITLE
Add shadow under the navbar

### ISSUE THREAD

**Issue by fardinzam** [acm-ucr/gardening-website#38]
- if you look closely you'll notice the navbar has a small shadow under the component which has not been implemented in the code yet
- add a box shadow at the bottom in Navigation.jsx under src/components
<img width="836" alt="Screenshot 2024-07-09 at 6 58 29 AM" src="https://github.com/acm-ucr/gardening-website/assets/55073341/a7d99692-2da0-4bb5-9f6d-72f51fc3fc45">

**Comment by medelm1** [comment]
To enhance the navbar's appearance with a more prominent box shadow, you might want to try using `shadow-2xl` instead of `shadow-lg` in `Navigation.jsx` under `src/components`:

```html
<Navbar className="bg-gardening-green-100 p-5 flex justify-between items-center shadow-2xl">
```

This will apply a larger shadow (`2xl`) and should provide the effect you're looking for. Feel free to adjust the shadow size (`xl`, `2xl`, etc.) based on your design preferences. Let me know if this helps!
